#!/bin/bash

apt update
apt upgrade -y
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:ondrej/php -y
sudo apt update
sudo apt install php8.0 -y
apt install php8.0-curl -y
apt install ntpdate -y
timedatectl set-timezone Asia/Jakarta
ntpdate asia.pool.ntp.org
apt install screen -y
mv screenrc ~/.screenrc
